In [1]:
%matplotlib inline

In [2]:
import torch
import numpy as np

In [3]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

In [4]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [9]:
x_ones = torch.ones_like(x_data)
print(x_ones)

x_rand = torch.rand_like(x_data, dtype = torch.float) # rand의 경우 자료형 정의 필요
print(x_rand)

tensor([[1, 1],
        [1, 1]])
tensor([[0.2106, 0.4470],
        [0.9069, 0.6246]])


In [10]:
shape = (2,3,)

rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(rand_tensor)
print(ones_tensor)
print(zeros_tensor)

tensor([[0.0039, 0.1965, 0.7372],
        [0.8066, 0.8617, 0.1739]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [11]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [12]:
# GPU가 존재하면 텐서를 이동합니다
if torch.cuda.is_available():
    tensor = tensor.to('cuda')

In [18]:
tensor = torch.ones(4, 4)
print('first row', tensor[0])
print('first column', tensor[:, 0])
print('last column', tensor[...,-1])

tensor[:, 1] = 0
#print(tensor)
print()
print('first row', tensor[0])
print('first column', tensor[:, 0])
print('last column', tensor[:,-1])

first row tensor([1., 1., 1., 1.])
first column tensor([1., 1., 1., 1.])
last column tensor([1., 1., 1., 1.])

first row tensor([1., 0., 1., 1.])
first column tensor([1., 1., 1., 1.])
last column tensor([1., 1., 1., 1.])


In [19]:
t1 = torch.cat([tensor, tensor, tensor], dim = 1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [30]:
t1 = torch.stack([tensor, tensor, tensor], dim = 0)
print(t1)
print(t1.size())
print()
print()
t2 = torch.stack([tensor, tensor, tensor], dim = 1)
print(t2)
print(t2.size())

tensor([[[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]]])
torch.Size([3, 4, 4])


tensor([[[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]]])
torch.Size([4, 3, 4])


In [32]:
# 두 텐서 간의 행렬 곱(matrix multiplication) 계산 -> y1, y2, y3 모두 같은 값을 가지게 됨
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)
y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out = y3)

print(y1)
print(y2)
print(y3)
print()
# 요소별 곱을 계산 -> z1, z2, z3 모두 같은 값을 가지게 됨
z1 = tensor * tensor
z2 = tensor.mul(tensor)
z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out =z3)
print(z1)
print(z2)
print(z3)
print()

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])



In [33]:
# 단일요소 텐서의 경우 item을 사용하여 python 숫자값으로 변환 가능

agg = tensor.sum()
agg_item = agg.item()
print(agg, type(agg))
print(agg_item, type(agg_item))

tensor(12.) <class 'torch.Tensor'>
12.0 <class 'float'>


In [34]:
# 바꿔치기 연산 (inplace 연산) -> 연산 결과를 피연산자에 저장하는 연산 / _ 접미사를 사용

print(tensor, '\n')
tensor.add_(5)
print(tensor) # 5가 더해진 값으로 피연산자가 변화함

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


In [42]:
# CPU에서 텐서와 Numpy 배열은 메모리 공간을 공유하기 때문에, 하나를 변경하면 다른 하나도 변경됨

t = torch.ones(5)
print(f't = {t}')

n = t.numpy()
print(f'n = {n}')

t.add_(1)
print()

print(f't = {t}')
print(f'n = {n}')

t = tensor([1., 1., 1., 1., 1.])
n = [1. 1. 1. 1. 1.]

t = tensor([2., 2., 2., 2., 2.])
n = [2. 2. 2. 2. 2.]


In [40]:
n = np.ones(5)
t = torch.from_numpy(n)
print(f"t: {t}")
print(f"n: {n}")
print()
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
n: [1. 1. 1. 1. 1.]

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
